# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - name: Git Config
      run: |
        git config --global user.name "vdegenne"
        git config --global user.email "vdegenne@gmail.com"
    ## Fetch remote information (since github actions is local)
    - run: git fetch origin
    - run: git branch -r
    ## Checkout the builds branch
    - run: git checkout -b builds origin/builds
    # - run: ls -l
    # - run: ls -l docs
    # - run: ls -l docs/assets
    ## Bring the master version before building
    - run: git merge -X theirs master --allow-unrelated-histories
    # - run: git pull origin master 
    - run: npm run build --if-present
    - run: git status
    - name: Push changes
      run: |
        git add .
        git commit -m "builds"
        git push -u origin builds
